# Generated by Django 3.1 on 2020-08-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200824_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(default='https://twitter.com/', max_length=300),
        ),
    ]
